### ISSUE TITLE
Could you please improve C syntax coloring?

### ISSUE THREAD

**Issue by r44083** [Briles/gruvbox#1]
Names of functions and strings have the same colors. Sometimes this creates confusion.

![alt text](https://habrastorage.org/files/691/bbd/e32/691bbde329be47e7802e33a93ef23ddd.png)

**Comment by Briles** [comment]
Does this look improved?
I kept the colors consistent with other languages. I could also consider changing the function name in the header if wanted.

![1](https://cloud.githubusercontent.com/assets/7333245/13639670/c7ca8f68-e5df-11e5-913f-0cb6dee4b4c9.png)

**Comment by r44083** [comment]
I think that in this case color gamma moved to the red area (preprocessor definition is are red and name of functions are orange to), so it can create uncomfortable feeling for some people.

**Comment by r44083** [comment]
What do you think about idea that make in C language functions color is №2 and strings color is №6 or №14 from this palette: https://camo.githubusercontent.com/cdb2f2e986c564b515c0c698e6c45b4ab5d725a9/687474703a2f2f692e696d6775722e636f6d2f776136363678672e706e67 ?

**Comment by Briles** [comment]
The colors of string will be staying as green as that is how they are colored in gruvbox for vim. I can however flip the colors you specified and use aqua as the function color, like so:

![2](https://cloud.githubusercontent.com/assets/7333245/13675299/f2bbaf5c-e6ae-11e5-8427-c9ba80b00e2f.png)

**Comment by r44083** [comment]
Wow, looks amazing. It is the best solution. Thank you.

**Comment by Briles** [comment]
This will make it into the next release. Thank You!
