### ISSUE TITLE
Custom app icon?

### ISSUE THREAD

**Issue by ebsen** [Briles/gruvbox#10]
You've done a tremendously great job with this, @Briles. Given the excellent iconography throughout the project, I'd love to see an app icon to match.

**Comment by Briles** [comment]
I added a couple different app icons to https://github.com/Briles/gruvbox/tree/master/extras/app-icons.

I'm not sure if the ICNS files work as I'm on Windows so I didn't have any way to test them.

Let me know if you have any problems.

**Comment by ebsen** [comment]
They both work fine on this Mac. 👍🏼
