### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by buildersbrewery** [Briles/gruvbox#13]
https://www.sublimetext.com/3dev

> Build 3116
> * Color Schemes: Added popupCss key, for defining default popup style sheets.

**Comment by Briles** [comment]
From what I have gathered, `popupCss` isn't fully implemented, but  what is implemented should be supported in [gruvbox 2.1.6](https://github.com/Briles/gruvbox/releases/tag/2.1.6). As more information comes out about this, I'll add support for it.
