### ISSUE TITLE
Can the file icons be enlarged?

### ISSUE THREAD

**Issue by antonioOrtiz** [Briles/gruvbox#14]
Love this theme! Essentially can the icons on the left be enlarged just a tad?

![screen shot 2016-06-28 at 12 06 14 pm](https://cloud.githubusercontent.com/assets/4282013/16422733/74084ae2-3d27-11e6-85b9-cd6e33a724ea.png)

**Comment by Briles** [comment]
Would you like both the folder icons & file-type icons enlarged? If you could give me a list of the file-type icons you want enlarged, I can start with those and go from there. 

If I do enlarge the folder icons, I will offer them as an alternate icon set.

**Comment by antonioOrtiz** [comment]
Yes—i'd like both enlarged (folder icon and file type icon). However, I don't want to give you extra work to do. To me (and this is obviously subjective) the .bowerrc, gulp, npm, sass and css look a tad smaller.

**Comment by jrappen** [comment]
@antonioOrtiz 

As you can see from the history

* @Briles addressed the folders in Briles/gruvbox@14e3ccb
* while I addressed the icons in Briles/gruvbox@e85a41e in PR #26
