### ISSUE TITLE
Selected Tab Indictator

### ISSUE THREAD

**Issue by Bond699** [Briles/gruvbox#17]
I LOVE this theme/scheme. You wouldn't believe how I tried before settling on this one...

There is one nagging issue. It's subjective. I'd like the the currently selected tab to be more obvious. An option to enable this:
![selected-tab](https://cloud.githubusercontent.com/assets/20736064/17336023/fa554920-58a1-11e6-84b5-412a563cb2b5.jpg)

**Comment by Briles** [comment]
I just added an option to underline the selected tab. This will make it into the next release after some more testing.

**Comment by Bond699** [comment]
Awesome, thank you!

**Comment by Briles** [comment]
This just went out with [2.3.0](https://github.com/Briles/gruvbox/releases/tag/2.3.0). Enjoy!
