### ISSUE TITLE
Request for adding to gruvbox-contrib list

### ISSUE THREAD

**Issue by morhetz** [Briles/gruvbox#2]
Hi, @Briles!
Your work on this sublime theme is unbelievable 🔥
Would you mind if I link this from [gruvbox-contrib ports list](https://github.com/morhetz/gruvbox-contrib#ports)?

**Comment by Briles** [comment]
That would be great! 
I went ahead and opened a pull request: morhetz/gruvbox-contrib#23
Thanks for asking and thanks for creating gruvbox :+1:
