### ISSUE TITLE
Oversized inline error

### ISSUE THREAD

**Issue by Stormherz** [Briles/gruvbox#22]
![oversized](https://cloud.githubusercontent.com/assets/235075/18885851/3fbf86d0-850f-11e6-9904-9b6c0be65608.png)

Is there a way I can tweak that? Looks really oversized.

**Comment by Briles** [comment]
are you using a plugin to show popups for build results?

**Comment by Stormherz** [comment]
@Briles nope, that's new inline errors presented in sublime (https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124)

**Comment by Stormherz** [comment]
@Briles hmmm, I think it was some kind of a floating bug with sublime itself - checked once again, everything's fine, sorry for bothering you =)
