### ISSUE TITLE
Problems with accented letters coloring in LaTeX

### ISSUE THREAD

**Issue by gustavobittencourt** [Briles/gruvbox#23]
Dear Brian,

First of all, congratulations for your work. This theme is terrific!

About the color scheme to LaTeX, I think there is something weird with the accented letters, take a look at the screenshot.

<img width="739" alt="captura de tela 2016-10-01 as 03 48 06" src="https://cloud.githubusercontent.com/assets/7130975/19012378/1b7bf9f2-878a-11e6-9b31-5adf1bc6941c.png">

Also, I'd like to suggest you to change the paragraph text color of LaTex from the actual #83A598 (I used SIP to get it in the CSS Hex, but I think is actually something near this tone) to a pastel like #FBF1C7.

Thank you again.

Best regards,

Gustavo Bittencourt

**Comment by Briles** [comment]
Thanks for reporting this! Which version of Sublime Text are you using? 

Also, if you could upload a snippet of the file in question (or one similar), it would help greatly.

**Comment by gustavobittencourt** [comment]
I am using *Sublime Text 3 Build 3126* for *Mac OS X El Capitan 10.11.6*.

I was adapting the file I'm working to create a minimal snippet and found something interesting: Commenting the lines `20` and `21` makes the highlight work flawlessly (and make the paragraph color be that pastel I told earlier).

I hope this can help.

<img width="1392" alt="captura de tela 2016-10-01 as 16 55 20" src="https://cloud.githubusercontent.com/assets/7130975/19016678/eff9a5d6-87f7-11e6-990f-dec869aeb29d.png">
<img width="1392" alt="captura de tela 2016-10-01 as 16 55 31" src="https://cloud.githubusercontent.com/assets/7130975/19016684/09984fa6-87f8-11e6-8593-612c04431c3e.png">

PS: I had to zip the snippet because github doesn't allow me to upload `.tex`.
[Snippet.tex.zip](https://github.com/Briles/gruvbox/files/504633/Snippet.tex.zip)

**Comment by jrappen** [comment]
The character `$` seems to cause the issue here:

/cc @randy3k @r-stein

**Comment by r-stein** [comment]
This issue is similar to https://github.com/sublimehq/Packages/issues/685. While creating the syntax definition it is not possible to match every command, which changes the meaning of the characters (you could even define such a command in your tex file).

I don't know a good solution for this, but you could put those definitions into a different file and `\input` that file to avoid the highlighting problems.

**Comment by gustavobittencourt** [comment]
Dear @Briles, @jrappen and @r-stein, I just saw your answers now that the issue was closed.

Thank you all for addressing my question. I will try to put these definitions in another TeX file or in a `.sty` package to see if it solves the problem! Regards!
