### ISSUE TITLE
[Bugfix Request] Parentheses Glitch

### ISSUE THREAD

**Issue by copoutolen** [Briles/gruvbox#32]
Weird Parentheses Behavior in C Expressions

I've recently installed the package, and so far it's been great to use it, but I've just run into a glitch regarding parentheses highlighting for simple C expressions, which surprised me quite a lot.

They both appear equally white when no space is added between the keyword and the first parentheses:

	- if()
	- while()
	- for()
	- do()
	- catch()

Adding spaces or tabs, however, will break rendering, causing the first one to show up darker for some reason.

	- if ()
	- while ()
	- for ()
	- do ()
	- catch ()

Here's a screenshot I took to illustrate the bug - It persists regardless of the gruvbox color theme I choose:

![error](https://cloud.githubusercontent.com/assets/18076392/25207147/f09fb1b8-2542-11e7-920a-b6b07053f695.png)

Thought I might as well notify it, any help is appreciated.

**Comment by copoutolen** [comment]
Upon further observing this behavior, I noticed C++ class constructors and operators both have darker parenthesis by default - exactly the breaking color as well. Maybe highlighting is getting the opener confused with an operator or something? Is Sublime Text itself causing this behavior?

**Comment by jrappen** [comment]
@copoutolen Your issue is syntax related and should be reported at:

* <https://github.com/sublimehq/Packages>
