### ISSUE TITLE
Option to make folder labels in the sidebar bold?

### ISSUE THREAD

**Issue by irrg** [Briles/gruvbox#38]
Would it be possible to get bold labels in the sidebar? I've tweaked indentation and spacing and indentation does offer a good view on hierarchy, but bold would help me a lot more on projects with a lot of components.

Great work on the theme!

**Comment by irrg** [comment]
Awesome, thank you!

**Comment by irrg** [comment]
Crap, I realized I wasn't clear enough. I was hoping I could distinguish folders from files by making folder labels bold but file labels regular. Hope that's still something we can do.

**Comment by Briles** [comment]
I believe there's already a default sublime preference setting that'll make folder labels bold: `"bold_folder_labels": true`.

**Comment by irrg** [comment]
A ha. Thank you.
