### ISSUE TITLE
Bracket Highlighter colors?

### ISSUE THREAD

**Issue by smlombardi** [Briles/gruvbox#4]
It would be nice if the bracket highlighter underlines (see image, under the `span` tags) were in a brighter Gruvbox color. like the accent color. Or am I missing something?

![screen shot 2016-04-04 at 3 06 20 pm](https://cloud.githubusercontent.com/assets/835148/14259873/f1d0549a-fa76-11e5-8466-f447661d5100.png)

**Comment by Briles** [comment]
By accent color do you mean one of red, blue, green, etc.?

 I can increase the brightness of the underline, but I would like to keep it neutral as everyone has different preferences.

If you're using the Sublime Text Bracket Highlighter plugin, you can set the tag underline color manually in the settings.

For example:

If you want the underline color to match the tag color (blue), find the scope currently coloring the html tag (`entity.name.tag`) and add it to your `Bracket Highlighter > Bracket Settings — User` file like so:

```json
"bracket_styles": {
        "tag": {
            "color": "entity.name.tag"
        }
}
```

**Comment by smlombardi** [comment]
I see.  I'll try that.  

I don't mind neutral, but they're a little hard to pick out.  I wouldn't want some hideous color, though.  I agree it would ruin the beautiful look of the theme.

**Comment by Briles** [comment]
I have bumped the bracket highlight colors up from `gray` to `fg3` -- a subtle increase but makes the highlight more visible.

If you desire other colors I definitely suggest overriding the Bracket Highlighter settings.

These changes will make it into the next release in a couple days.

![untitled-1](https://cloud.githubusercontent.com/assets/7333245/14263453/b269a948-fa88-11e5-9822-abfa47ff4b6a.png)

**Comment by smlombardi** [comment]
Sweet, thanks.
