### ISSUE TITLE
Errors after the latest update: "Error loading colour scheme"

### ISSUE THREAD

**Issue by nick-s-b** [Briles/gruvbox#44]
Hi all,
Sometime yesterday gruvbox package was updated and immediately ST3 theme stopped working for me. Every time I start ST3, I get this error message:
````
Error loading colour scheme Packages/gruvbox/gruvbox (Dark) (Medium).sublime-color-scheme: Error parsing plist xml: expected < in file Packages/gruvbox/gruvbox (Dark) (Medium).sublime-color-scheme on line: 1
````

And the theme doesn't work.

Is there anything I can do other than picking another theme? Thanks!

### Environment

```text
gruvbox:

    version: latest
    installed via Package Control: True

Sublime Text:

    channel: dev
    version: 3144
    platform: Linux
    architecture: x64
```

**Comment by Briles** [comment]
Hello,

gruvbox >= v3.0.0 dropped support for .tmThemes and added support for the .sublime-color-scheme format which was introduced with Sublime Text 3170. The package control repository hasn't been updated to prevent installation of gruvbox versions incompatible with your version of Sublime Text.

You have a few options at the moment:

- update to Sublime Text 3170 or later
- manually install [gruvbox 2.4.2](https://github.com/Briles/gruvbox/releases/tag/2.4.2) which supports .tmThemes

I'll be trying to update the package control repository to prevent this from happening, but I can't provide any ETA for when that will be available.

**Comment by nick-s-b** [comment]
Thank you @Briles! I cannot update ST3 at the moment until the project is finished (not my decision) so I've downgraded the gruvbox and added it to the list of packages not to update until this is somehow mitigated. Thanks for a reply! Much appreciated!
