### ISSUE TITLE
Gruvbox themes are not persistent

### ISSUE THREAD

**Issue by qazip** [Briles/gruvbox#48]
# Gruvbox' theme is not selected after reopening ST.

## A summary of the issue

This started happening with the latest update I believe. First, I opened ST and noticed that gruvbox was not being used (I use a dark theme and ST was white for some reason). I activated/selected a gruvbox' theme again, but after closing and re-opening ST, gruvbox is not persistent, that is, it goes back to a white theme.

### Environment

```text
gruvbox:

    version: 4.0.0
    installed via Package Control: True

Sublime Text:

    channel: stable
    version: 3207
    platform: Linux
    architecture: x64
```

EDIT: I selected the dark (hard) theme and now, when selecting another theme (dark medium, for example), when re-opening ST, the theme is always the dark (hard) one.

**Comment by Briles** [comment]
Take a look at your user `Preferences.sublime-settings`. Specifically the `theme` and `color_scheme` key values.

With the latest updated, 4.0.0, the 6 different UI themes were merged into a single theme - `gruvbox.sublime-theme` or just gruvbox. It sounds like your Sublime Text is still trying to find the old, unmerged versions.

The theme and color_scheme key values in your user preferences should match one of the combinations below:

```
// gruvbox Dark Hard Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Dark) (Hard).sublime-color-scheme",
}
// gruvbox Dark Medium Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Dark) (Medium).sublime-color-scheme",
}
// gruvbox Dark Soft Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Dark) (Soft).sublime-color-scheme",
}
// gruvbox Light Hard Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Light) (Hard).sublime-color-scheme",
}
// gruvbox Light Medium Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Light) (Medium).sublime-color-scheme",
}
// gruvbox Light Soft Contrast
{
  "theme": "gruvbox.sublime-theme",
  "color_scheme": "Packages/gruvbox/gruvbox (Light) (Soft).sublime-color-scheme",
}
```

**Comment by Briles** [comment]
it looks like there might be an issue with the `gruvbox: Select Theme` command. The theme should persist if you don't use the command.

I'll work on getting this resolved. Thanks!
