### ISSUE TITLE
Styling on Plain Tasks

### ISSUE THREAD

**Issue by ValBontrager** [Briles/gruvbox#49]
This Overwrites all plaintask color_scheme settings. I have tried to change it to something different, but it just goes back to some default layout of Sublime, not even Plain Tasks. 

gruvbox:
    version: 4.0.1
    installed via Package Control: True

Sublime Text:
    channel: stable
    version: 3.2.1
    Build: 3207
    platform: mac

**Comment by Briles** [comment]
Could you provide the contents of your PlainTasks.sublime-settings (`Preferences > Package Settings > PlainTasks > Settings - User`)?

I don't think the issue you report is specific to the gruvbox theme. PlainTasks determines which color scheme to use based on it's own default settings or the user settings you provide for it. gruvbox doesn't automatically configure any PlainTasks settings nor should it be overwriting anything.

**Comment by ValBontrager** [comment]
Yes. I was using Gruvbox for the styling.
{
"color_scheme": "Packages/gruvbox/gruvbox (Dark) (Medium)
NDC.sublime-color-scheme",
"date_format": "(%m-%d-%y %H:%M)",
}

It seems like nothing will overwrite the monokai settings. Gruvbox is the
latest change to my sublime, but you're right, it could be something else.

Thanks for your response,
Val

**Comment by Briles** [comment]
I'm not able to reproduce any issues using your PlainTasks configuration. It uses the gruvbox color scheme that is specified and not the monokai settings.

![plaintasks](https://user-images.githubusercontent.com/7333245/56614953-24755c80-65e8-11e9-8b30-446231dc198d.png)

---

You might have better luck posting your issue over at the [PlainTasks project](https://github.com/aziz/PlainTasks/issues). I'm not a user of PlainTasks and i'm not all that familiar with it.

**Comment by ValBontrager** [comment]
Thanks. I closed out all the windows and restarted and it worked. I have no
idea. I'm so sorry to bother you, but I appreciate you looking into it!!
