### ISSUE TITLE
Modified tabs do not appear to be working

### ISSUE THREAD

**Issue by paradox41** [Briles/gruvbox#5]
Version: 2.0.0

Settings:

```js
"gruvbox_accent_orange": true,
"gruvbox_colored_tooltips": true,
"gruvbox_enable_tab_borders": true,
"gruvbox_underline_modified_tabs": true,
// I have tried with one / both of these. No luck.
"gruvbox_underline_modified_tabs_thick": true,
"gruvbox_sidebar_comfortable": true,
```

Screenshot:

![screen shot 2016-04-07 at 9 38 43 am](https://cloud.githubusercontent.com/assets/2791730/14352867/8b670318-fca4-11e5-8cc1-7872e0a69af5.png)

Please let me know if you'd like anymore information.

**Comment by Briles** [comment]
Seems to be an issue with enabling tab borders. I'll have it fixed shortly. Thanks for reporting this!

**Comment by Briles** [comment]
This is fixed in the new release, which could take an hour or so before it shows up on Package Control.

Thanks!

**Comment by paradox41** [comment]
Awesome! Thanks for the quick response.
