### ISSUE TITLE
Gauging Interest for Icon Animations

### ISSUE THREAD

**Issue by Briles** [Briles/gruvbox#6]
The purpose of this issue is to gauge interest in having animated icons added to the themes.

I'm not a designer or artist and Sublime Text is limited in its animation capabilities so the animations would be simple.

As an example, here is a possible animation for the tab close icon:
![Tab Close Animation](http://i.imgur.com/LVSKi6c.gif)

or even folder icons:
![Folder Animation](http://i.imgur.com/6ibwhE7.gif)

or even Find & Replace icons:
![In Selection Animation](http://i.imgur.com/p4FsNzv.gif)

All animations would be enabled by a `User Preferences` option.

Please express your reactions here and if enough interest is shown, I will begin work on animated icons and log my progress here.

Thanks!

**Comment by pdanpdan** [comment]
I think it would look nice, it would be a good addition to this theme.

**Comment by mzgnr** [comment]
Thanks for your work. It would look nice !

**Comment by Briles** [comment]
[2.1.3](https://github.com/Briles/gruvbox/releases/tag/2.1.3) Should be up on Package Control soon and contains animated tab close & directory icons. Animated icons can be enabled with the setting `"gruvbox_animate_icons": true,`

**Comment by buildersbrewery** [comment]
* Find & Replace icon sets (default / midstroke / thick) aren't included yet I suppose?
* Folder and tab close icons look good.

**Comment by Briles** [comment]
@buildersbrewery The Find & Replace icons will mostly likely be the last icons to be animated as I haven't yet thought of nice animations for most of them. The next icons to be implemented will probably be the panel-menu icon & the more-tabs/search-history icon.

 At this point I'm only concerned with the default icon set. After more animated icons are added and if people seem to like them, I may consider adding animations for the other icon sets.

**Comment by jrappen** [comment]
![gruvbox light hard ndc](https://cloud.githubusercontent.com/assets/8577450/15587472/a4ebe428-2389-11e6-93a7-ee432f42c4b6.png)

* Gruvbox Light Hard NDC
* Build 3113 dev (Portable) on Windows 10 Pro x64
* v2.1.3

**Comment by Briles** [comment]
@jrappen Thanks for reporting this, I just fixed it with 22cbc4698821dc9120d9ff66fe1027ea3365a01e and released [2.1.4](https://github.com/Briles/gruvbox/releases/tag/2.1.4), which should be up on Package Control shortly

**Comment by jrappen** [comment]
[v2.1.4](https://github.com/Briles/gruvbox/releases/2.1.4) works for me, thanks for the quick fix.

**Comment by Briles** [comment]
Animated panel switching icon should make it into the next release. :tada: 

![animation 3](https://cloud.githubusercontent.com/assets/7333245/15732167/f6b1ea8c-2848-11e6-9853-c57efd3612c1.gif)
