### ISSUE TITLE
For other ed

### ISSUE THREAD

**Issue by Alexey-T** [Briles/gruvbox#8]
Hi
Maybe possible to 'port' theme to CudaText?

**Comment by Briles** [comment]
I appreciate the enthusiasm but porting the theme to other editors is not something I'm interested in at this time. You may have some luck asking in https://github.com/morhetz/gruvbox-contrib

**Comment by Briles** [comment]
@Alexey-T 

I went ahead and created some themes for CudaText: https://github.com/Briles/gruvbox-cudatext

Should I open a PR at https://github.com/Alexey-T/CudaText and submit them there?

**Comment by Alexey-T** [comment]
No- enough;I will take zip file. Good work. I test

**Comment by Alexey-T** [comment]
In Addonmanager now. Thanks
